### ISSUE TITLE
pre_trained_issues

### ISSUE THREAD

**Issue by Flora77** [koflera/DynamicRadCineMRI#4]
Hello:
How can I train my own model to get the pretrained data(model_E3C2K4.pt)? Could you please offer the code for model training? Thanks a lot!

**Comment by koflera** [comment]
Hi Flora77, thanks a lot for the interest in our work.
Unfortunately, I cannot provide the data used for training for data-protection related issues. 

Apart from that, in order to train a model, you would simply need to create your own dataset based on your ground-truth images, trajectories, coil-sensitivity-maps etc, similarly as in the `basic_example.py` script, see
https://github.com/koflera/DynamicRadCineMRI/blob/main/basic_example.py.

Then, the CNN-based reconstruction network can be set up similarly as in 
https://github.com/koflera/DynamicRadCineMRI/blob/main/cnn_usage_example.py.

Finally, you would need to write a simple for-loop to iterate over your data and perform back-propagation, i.e. something like

```
# import all the relevant modules etc
....

cnn_block = XTYTFFTCNN(n_ch=2, n_enc_stages=3, n_convs_per_stage=2, n_filters=4)
model = NUFFTCascade(EncObj, cnn_block, nu = 1, npcg = 8, learn_lambda=True, use_precon=True, mode='fine_tuning')
loss_fct = nn.MSELoss()
optimizer = torch.optim.Adam(model, lr = 1e-4)
dataset = YourDataset(...)
dataloader = DataLoader(dataset = dataset, ... )
for epoch in range(n_epochs):
    for _, data in enumerate(data_loader):
        xu, xf = data
        optimizer.zero_grad()
        xreco = model(xu)
        loss = loss_fct(xreco , xf)
        loss.backward()
        optimizer.step()
        .... 

```

where the choice of the cnn-block above corresponds to the one you have mentioned (E3C2K4). 

We didn't use anything more sophisticated than that.

I hope that helps :)

Best,

Andreas

**Comment by koflera** [comment]
@Flora77: I am closing this since it is not really an issue. Feel free to reach out again!

**Comment by koflera** [comment]
@Flora77: I am closing this since it is not really an issue. Feel free to reach out again!
